apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-password
  namespace: dev
spec:
  encryptedData:
    password: AgBaZkAP6md6liPU7EUKWv0VMFjYtYKkMUrUgvzBR1R1RiALKMpJNXbGKdGehRptGkz6pr3MNuADpPpWiZPXIJzqOhz/yBx8ynX4Jd/oHBnn0UbU+oT0DxJlLTPM4AFNwIEQoZ8kIJbUWF8Kt2RmwOgIsHpUOKLOzd8SvR6jUEHYLkTZHKECa/SnPYE7IZ5xuFD2BH5TR44kyUHtxjk2mdNGkxduBIzOMPh7IrnqQVpscbF6mFYHrzNAxKeM8ek8P3RZbyZWEVKBA4wvvPVKSmApGDNxE/PQ12lxMwqELVfMzBZRTwlYVSApvJbDmFo0MA3EEG2YSnZABUTw7NhZwsceV/rrpkeadrolzqu+uxoWvusgRbuuoXJCHw/+t2TCSh7fmZDm00IIpqTiRjDSSXT8dPmb38UdXZ5H1qi4WH9rujUMeU94ibU0tMR2s+Ji6ZE+g2euY02hm31bGx3XGrm+fxk4h/6s6oRJ7Cskk75zjZMarmchBzpLCyrNbEKCE2VeKgG7/eqaHLNqqhDVHDkpZJG/DuY7kwLN+1NbPm7FkwAckcosUxpxi2AipWRt6G9Mxq7SE2KhCK1h6yRwTgLzkHMRf8T0+zughHRrGQ4+Ab3EaE4cvUYEBV/E87pWynmlefbqM3aJ3IcpP+E0iYQSxSLVS2/Gue/bK2BXNpJdQJXNWO2M7YtpnTuXHbP/5vdbnqmsvFufp6U=
  template:
    metadata:
      creationTimestamp: null
      name: database-password
      namespace: dev

