apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-password
  namespace: dev
spec:
  encryptedData:
    password: AgA6f5NJZsoGsINe3YJ3HHPTF63lMSoJNA0IbYDiJW7qA17aj21LVqZ19T/rAIe0qKxCnKFw4c0b0ohSl2AGzE2azUOGcj84wlPhQZcBM0ke3WVsnLFqCZXlDr+EuA5UvqTB9HQutIFylXQ10hWFAzwn9iDxvrzQgHEjCXqsxfxh/qPb4usJFhJAZisMwHw8TZGI9e3QVJMfnejCf96+BncU3Enq905oIy40PmuMu7WsTUOTPc9YUjDwlgsvtRzQpJoJ8b7OEWrISegZov4KZBJcZ9ZDvd93Dg28pOD3eJwo6gFhyVFKUtf8DRgwS9IJ0+D5hsJa3qf0bZd0AT9IOuooafzhuNM1buOkMp+vcuOcLXOtv/jWkDmSD0BxJg1aN2DaW7gXlx+oPkJ9NIc2NK3ejYpg+9rLghWnqof2ZCeZv313vqfW573NbVeHyjANacLVvnuK3sjCuof+lk+uRiV9xcoHScmRT7g17GAbc4hY26QuGrHc3YiTHYxNMGZFaY4RChQE6PgwB0ZoFN90YIBKdlin9+yn++HfahDyzxENHMwEw70ytIKnsxwpJIUpkoP8tW5CeTSgS1FW+4bC6voEvOVPgTZUNI4Codrd7tVoFJJhajQ9qGSBPMcz5V5A0CZIxlle7t+bV8iFhrMhQf5ThkcH26eCC5MBvDRXVPfDY72/qb7GA941vFH+/AkJKI5jEfOCUMfHvso=
  template:
    metadata:
      creationTimestamp: null
      name: database-password
      namespace: dev

